#!/usr/bin/env node

const mdtoc = require("./src/mdtoc.js");

var argv = require('yargs')
	.usage('Usage: $0 file/dir')
	.example('$0 README.md -d 3', 'Create a ToC for \'README.md\' using ### as the top level header.')
	.demandCommand(1)
	.alias('d', 'header')
	.nargs('d', 1)
	.boolean('tags')
	.default({'d':2, 'tags': true})
	.argv;

argv._.forEach(item => {
	mdtoc.run(item, argv.header, argv.tags)
});



